// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stdeueuwrtddffcfbvhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0ZGV1ZXV3cnRkZGZmY2ZidmhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NTQwNDMsImV4cCI6MjA2OTUzMDA0M30.ax4MSzRcdMxt8_yVI78_K3lI2w63Q987EEsDTuEcfDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});